### ISSUE TITLE
Parameters in gen3_macro.xacro

### ISSUE THREAD

**Issue by crislagarde** [Kinovarobotics/ros_kortex#121]
Hi,

Parameters **parent** and **origin** in gen3_macro.xacro are really needed? I cannot see where they are used, so it could be possible to remove them from the package?

Thanks!

**Comment by alexvannobel** [comment]
Hi @crislagarde ,
Sorry for the long delay.

Currently, those parameters are indeed unused in `ros_kortex` (but from the end-user perspective actually invisible because the default values are provided in `kortex_robot.xacro`), but I chose to let those values there because it would then be easier for a third-party integrator to add our xacro e.g. on a mobile platform.

I agree for an application where the arm is not mounted on anything, those parameters are useless and you can remove them from the xacro files without problem in your branch or fork, but I won't remove them from `ros_kortex` for the reason above.

Best,
Alex
