### ISSUE TITLE
Gen3 is not moving

### ISSUE THREAD

**Issue by hadimohandes** [Kinovarobotics/ros_kortex#134]
Hi 

we have bought a Gen3 Kinova arm from your company at SFU.
so far, I am able to use the gazebo simulator and send commands to the robot in simulation. 
I am now trying to connect to the real hardware. after I run the kortex driver node, I can see all the rostopics are generated. 
I can also go to the web application and change the angular values and meanwhile see the change in the following: 
rostopic echo /my_gen3/joint_states
but when I send commands like joint trajectory commands or run the default examples (moveit_example.launch) you have put in the examples' directory,  I get an error and the robot does not move.
I have attached the error file from the driver node terminal. 
Has anyone faced the same problem? 

[error.txt](https://github.com/Kinovarobotics/ros_kortex/files/5575353/error.txt)

**Comment by alexvannobel** [comment]
Hi @Hadimohandes ,

I have a couple questions to try and find the problem:
1. With what command do you launch the example(s)? Did you only try the MoveIt example?
2. Did you modify the examples? If yes, can you provide the code?
3. What is the full output of the `kortex_driver` node after you started it?
4. Do you see the robot in RViz and is it in the same position as the real robot?

Cheers,
Alex

**Comment by hadimohandes** [comment]
Hi Alexander,


Thanks for your reply.

I assume Santiago Moya has sent you the chain of emails and also the outputs.

Here are the answers to your questions:

1: yes, moveit example

2: I have not modified the example

3: I will attach again here

4: yes, I see the robot in Rviz the same the real robot's configurations


Thanks for your help


Best,

Hadi


________________________________

**Comment by alexvannobel** [comment]
Hi @Hadimohandes ,

This is a most bizarre error. It seems like the arm either starts validation of the trajectory or never receives the call, but the action server goes in the corresponding state.

What is the starting position of the arm when sending it the MoveIt trajectory? Can you go in the WebApp, bring it to Home position and then try this again? I don't see why it would be related to starting position but it's worth trying.

Also, can you show the output of the `kortex_driver` node (before even running the example) when it starts? It's worth checking for errors in this log too.

Best,
Alex

**Comment by hadimohandes** [comment]
Hi Alex,


I did as you suggested (moved the robot to the home position) and it's working fine now.

but isn't there any way to do this without homing the robot?

we haven't faced this issue in simulation.

I will add the output of kortex driver in my next msg.

Thanks


Best,

Hadi

________________________________

**Comment by alexvannobel** [comment]
Hi @Hadimohandes ,

I think the arm actually complains that the starting position it is in is out of bounds for a PreComputed trajectory (which MoveIt uses).

A workaround would be to run a custom node which checks for this specific actuator's position upon starting the `kortex_driver`, and send a joint command to make it "in bounds" (e.g. if actuator's command is 150.01 and needs to be under 150.00, send a 149.9 command to make sure the actuator is ready to start a MoveIt trajectory upon boot). I had in mind something like [this](https://github.com/Kinovarobotics/ros_kortex/blob/kinetic-devel/kortex_examples/src/full_arm/example_full_arm_movement.cpp#L184-L214).

I'll keep this issue open because I might add this kind of check on startup for next release, but this won't be added in the short term.

Best,

Alex

**Comment by JaeYoungLee79** [comment]
I empathy for first question. 
We spend much time to search and to solve for error with running examples.
Just we can control robot. where is Control Example?
1. Desire X,Y,X : waypoint example is run
2. Desire Joint : ????
3. or Advanced is Current Control : ????

That's all. 
Unfortunately, kortex example are mixed. Code does not have enough explanation.
In Korea, new job position emerging for kinova control application.

**Comment by felixmaisonneuve** [comment]
I forgot to close this issue, but it was fixed with #184 and #185. Now, if the arm is out of bounds when launching the driver, each joint will move to the closest point "in bounds". 

@JaeYoungLee79, I am not sure your comment is related to the original issue. 
We have plenty of examples that show how to move the arm in different scenarios. Please open a new issue and I will help you there, but there is no point continuing on this thread.
