### ISSUE TITLE
Gen3 lite blending radius

### ISSUE THREAD

**Issue by lingxiaomeng** [Kinovarobotics/ros_kortex#156]
Does the blending radius for Gen3 Lite in waypoints must be 0?
when I set the blending radius to non-zero, the robot arm does not move.

**Comment by felixmaisonneuve** [comment]
Hi @lingxiaomeng,

Can you show me what your code looks like and the output of the error you get?
Enpoints should have a blending radius of 0 (otherwise ignored).

You can also use `goal.use_optimal_blending = true;` to use optimal waypoints blending radius without having to set them yourself (if that is something usefull for you)

Best, 
Felix

**Comment by felixmaisonneuve** [comment]
Since this thread seems to be inactive, I will close it. 

If you still encounter this issue, comment / re-open it or create a new issue.

Regards,
Felix
