### ISSUE TITLE
Release request of v2.2.3

### ISSUE THREAD

**Issue by 708yamaguchi** [Kinovarobotics/ros_kortex#187]
## Summary

Release request of v2.2.3, which includes https://github.com/Kinovarobotics/ros_kortex/pull/173

## Use case

We use kinova gen3 lite robot with v2.2 firmware.
https://www.kinovarobotics.com/en/resources/gen3-technical-resources

We want to use https://github.com/Kinovarobotics/ros_kortex/pull/173 feature with this firmware.

## Alternative

Currently, we use our original branch.
https://github.com/708yamaguchi/ros_kortex/tree/develop/spot

## Possible issues

I think there will be no problem by this feature.

## Additional context

cc @knorth55 @sktometometo

**Comment by knorth55** [comment]
I would like kinovarobotics to make a separate branch for v2.2.x, not v2.3.x.

**Comment by felixmaisonneuve** [comment]
Hi @708yamaguchi and @knorth55,

If I understand correctly, you are using an old firmware version, which means you cannot use any commit past `f0218097604a902cf8bfc65db64ef3aa5eefb455`. 
What you want is an another branch forking from a commit before the 2.3 release that contains the current updates to our repo. 

Did I understand it correctly?

Regards,
Felix

**Comment by knorth55** [comment]
@felixmaisonneuve yes, your understanding is correct.
We want a branch which support v2.2.x, and we can make a backport PR to follow the v2.3.x branch.

**Comment by felixmaisonneuve** [comment]
Then the answer is no, we will not make a separate branch for v2.2. It is better to simply update the arm firmware to 2.3.

We support ROS Melodic and ROS Noetic, which means we would need 2 branches for v2.3 (Noetic and Melodic) to also 2 branches for v2.2. Then, for each new modifications, we would need to duplicate the work to 4 branches. Plus, we would need to test with a v2.3 arm *and* a v2.2 to make sure everything is working fine. this would soon become overly complex (e.g. if a modification is not working on v2.2). 


Basically, it would require **a lot** of work to maintain for little to no gain.

Again, the easiest solution is to update your arm firmware.

If you absolutely want to keep v2.2 (for whatever reason it is), you will have to manually update your fork of the repo. There is plenty of ways you can do it. For example, you can add `.diff` on the link of a Github PR (e.g. https://github.com/Kinovarobotics/ros_kortex/pull/173.diff) to get a diff file of that particular PR. You can then use `git apply file.diff` to apply it to your fork. If your lazy, you can automate it using a bash script like `curl -L ${1}.diff > file.diff; git apply file.diff;` (not tested). Another way would be to generate a diff file between 2 commits using `git diff`. 

The point is, *you* would have to deal with the conflicts/incompatibilities and we will have no garanty that it will work in the end. 

I will close this issue since this is not something we will implement, but thank you for your suggestion.
If you have any other question feel free to leave a comment and I will answer you.

Regards,
Felix

**Comment by knorth55** [comment]
We know it is a lot of work.
But, in other part, following the new firmware again and again is a hard work, too.
Between v2.2.x and v2.3.x, there are huge changes in one PR (#154), and we need to check and change our codes.
We are afraid of changing the master branch with huge PR again and again.

We can work on our fork, but if we work on our fork, it is not beneficial for everyone in terms of open source because every one do their improvemen in their forks. 

Anyway, I can understand your decision. It makes sense.
We will try to follow v2.3.x, but it would require some time to check our programs.
