### ISSUE TITLE
The degrees of freedom specified in the launch file doesn't match the detected number of actuators

### ISSUE THREAD

**Issue by JDchen-Jaden** [Kinovarobotics/ros_kortex#211]
Hi!

I replace Gen3 7DoF with Gen3 6DoF. When I execute `roslaunch kortex_driver kortex_driver.launch`

An error appears shows as follows: 
`[ERROR] [1641496832.705056971]: The degrees of freedom specified in the launch file doesn't match the detected number of actuators, shutting down the node...`

`[ERROR] [1641496851.650546085]: Action client not connected: gen3_joint_trajectory_controller/follow_joint_trajectory
`

I tried to edit the driver file, however, it displays unreadable code. 

The WebApp controls the robot well. Do I need to rebuild the `ros kortex`? It would be appreciated that if anyone can help with this issue. 

Thanks,
Jaden

**Comment by felixmaisonneuve** [comment]
Hi @JDchen-Jaden,

That's because launching the driver uses default parameters (defined in [kortex_driver.launch](https://github.com/Kinovarobotics/ros_kortex/blob/noetic-devel/kortex_driver/launch/kortex_driver.launch)), and these are defined for 7dof arms. 

You could either change the default values in said launch file or pass the arguments when launhing the driver like this : 
```
roslaunch kortex_driver kortex_driver.launch dof:=6 vision:=false
```

See [Usage section](https://github.com/Kinovarobotics/ros_kortex/tree/noetic-devel/kortex_driver#usage) for more informations.

Hope this helps,
Felix
