### ISSUE TITLE
Inconsistency between mass values of Robotiq 2F-85 gripper provided in Gen3 User Guide and URDF.

### ISSUE THREAD

**Issue by RKJenamani** [Kinovarobotics/ros_kortex#212]
I have been trying to implement a gravity compensation controller for my Gen3 6DoF fitted with a Robotiq 2F-85 gripper. However, it is not working well due to what I believe are inconsistencies in the gripper URDF. 

In the Gen3 User Guide provided on [Kinova's website](https://www.kinovarobotics.com/product/gen3-robots), the mass of the Robotiq 2F-85 gripper is specified to be 0.925 kg (Page 69, Section "Robotiq 2F-85 Gripper tool configuration"). However, the sum of masses of all the links in the [URDF](https://github.com/Kinovarobotics/ros_kortex/tree/noetic-devel/kortex_description/grippers/robotiq_2f_85/urdf) provided for this gripper model in this repository comes out to be around 0.36 kg. While this issue would better suited for the source repository: [https://github.com/ros-industrial/robotiq](https://github.com/ros-industrial/robotiq), the source repository has become unmaintained. :( 

Any help/clarification with this would be much appreciated. Thank you!

**Comment by felixmaisonneuve** [comment]
Hi @RKJenamani,

I have looked a bit at this and I will try to summarize my thought on it. 

0.925 kg is the correct weight for the Robotiq 2F-85 gripper. 

The sum of all the links do end up at 0.36 kg. However, this weight does not include the pads mass, which is not specified in the xacro file.
Also, I don't know if the robotiq_arg2f_base_link mass includes all the hardware, or if it only includes the shell. In which case, the actual mass for a real gripper would be heavier, since it has a motor in it. I think ~220g is a bit light for such a "big" piece if it includes a motor and sensors (and other hardware) in order to make the fingers move, but maybe I am mistaken. 
Those 2 factors might explain why we end up with a much lighter mass. 

All the xacro are coming directly from the Robotiq github repository you have linked, and, if they are not accurate, it is hard for us the validate the data. 
If you compare the files, you will see that all the mass and inertial parameters for the 85 gripper in the xacro files are copied directly from the 140, so I am not even sure the mass is correct for the fingers and knuckles links on the 85. Looking at the original robotiq repo, `<inertial>` tags are commented for the 85 gripper, so I don't know if they actually validated the data for this gripper. 

I know you have been told to increase each component to reach the correct 0.925 kg. I would also suggest to add a `<inertial>` tag (with a mass) for the pads : https://github.com/Kinovarobotics/ros_kortex/blob/fa072f13b500b399e109bb146891c3e9ebb830cc/kortex_description/grippers/robotiq_2f_85/urdf/robotiq_arg2f_85_model_macro.xacro#L107-L128

I suppose you could also check if you want to increase the base_link mass more instead of the finger and knuckles. 

Do you need to be very precise with the gripper's mass? Why do you need this?

Regards,
Felix

**Comment by RKJenamani** [comment]
Hi @felixmaisonneuve,

Thank you very much for your help! I required the gripper's mass for implementing a gravity compensation controller. 

I tracked down the source of the current gripper URDF, and the first [PR](https://github.com/ros-industrial/robotiq/pull/16) that uses it has comments “I recommend we remove mass/inertia values. Very few ROS-I packages have these values because its hard to verify them” and “I'll log internally that we should publish the inertial data of the 2F gripper”. This does not spark confidence, and the gripper model also seems to have changed over the years.

Considering the uncertainty around the accuracy of the values mentioned in the URDF, I decided to make all its inertia values zero, and create an additional dummy link with the combined inertia values of the whole gripper (which the Gen3 User Guide Doc mentions). This should work as long as the fingers of the gripper do not change their position during execution (which is true for our use case).

**Comment by RKJenamani** [comment]
Once I've validated the correctness of the updated gripper URDF I am using, I can create a PR for it on this repository. However, the gravity compensation controller that I'm working on is still not working perfectly (due to what I think are issues with torque control).

**Comment by felixmaisonneuve** [comment]
Sure, if you open a PR with this new value, I will make sure to review it.

Best,
Felix
