### ISSUE TITLE
Torque offsets - gripper and alternatives to WebApp

### ISSUE THREAD

**Issue by mattia-risiglione** [Kinovarobotics/ros_kortex#237]
Hi everyone,

 when running the Kinova Gen3 arm in torque control, I reset the torque offset every time I restart the arm. 
Something I noticed is that this procedure has to be done without any gripper mounted at the end-effector, otherwise I do get some drifts afterwards. Is there any explanation about that? 
When I reset the offset without gripper, and I plug that afterwards with gravity compensation taking care of the gripper's load, then it works fine and the arm can compensate gravity in any configuration. I would really like to find a solution with the gripper mounted on since the start, I could save time.

Additionally, I am interested in a faster procedure for removing these torque offsets, which I do not see them as constant value (please, correct me if I am mistaken). I do get all torque offsets 0 when using the api from the torque control example with a simple code to print torque offsets like that:

```
for (int i = 1; i < 8; i++)
   {
       auto torque_offset = _m_actuator_config->GetTorqueOffset(i);

       std::cout << "TorqueOffset: " << i << " " << torque_offset.torque_offset() << std::endl;
   }
```
What am I doing wrong?
The question here is: what is the alternative to the WebApp to reset torque offsets?

Lasty, if the arm is placed on  a base in a position that is not vertical, how to deal with the reset of torque offset?

Thanks,

 Mattia

**Comment by felixmaisonneuve** [comment]
Hi @mattia-risiglione,

You might not like me for this, but here it is anyway : 

Setting the actuator torque zero (either from the API or the WebApp) must be done when all the actuators are under no load - which is only possible when all the joints are at their zero position and the base is vertical (in theory it would be feasible with the arm horizontal in a configuration with zero load, but cross torque will make it very inaccurate). In any other configuration, the actuators will be measuring the torque required to hold the robot's weight.

Regarding your question concerning the set zero with the end effector, you do not need to remove the gripper to do so, you are only experiencing issues because your arm is not vertical.

It seems that the "Set zero torque" functionality may not do what you believe it does. In short, the strain gauges/torque sensors in the actuators only measure a variation in torque, so the "set Zero" just resets the reference to provide users with an absolute measurement. In theory this should be only necessary once after the robot leaves production, but in practice it can be useful to compensate for wear on older units or temperature drift.

If you are looking for a way to get the robot's hand-guiding function to work properly in a non-vertical orientation, simply modify the gravity vector in the Web App configuration.

If you are looking for a way to obtain the gravity model of the robot, it is not possible via the Kortex API, however we can recommend using [roboticslibrary.org](http://roboticslibrary.org/), which is open source.

-------------------------------------------------------------------------------------------

I would have added more info, but I think it answers all of your questions. 
I'll be glad to help you more if there is still something that is unclear.

Best,
Felix

**Comment by felixmaisonneuve** [comment]
Hi @mattia-risiglione,

can we close this issue? 
I do not have other informations to give you on this topic

I will close it anyway in a couple weeks if I do not get an answer from you

Regards,
Felix
