### ISSUE TITLE
Is it avaliable to achive torque control of  Gen3 with a more simplify method?

### ISSUE THREAD

**Issue by ChanSir-QZ** [Kinovarobotics/ros_kortex#240]
## Summary

Define an object for the Gen3 to handle the control signals and read the sensors. Using the method robot.control() you read the joint values at 1kHz.
Refer to https://github.com/cpezzato/active_inference/blob/master/AICpanda.cpp

## Use case

Why is this feature needed?

Torque control could be used for different kinds of optimazation.

**Comment by felixmaisonneuve** [comment]
Hi @ChanSir-QZ,

I think topic relates more to our Kortex API (in our Kortex repo). Are you using ROS? Is there a reason why you are asking this in our ros_kortex repo? Not that it changes anything, I am just curious.

What do you think could be simplified on the torque control?
We provide an example on how to use the torque control in our kortex repo : https://github.com/Kinovarobotics/kortex/blob/master/api_cpp/examples/108-Gen3_torque_control/01-torque_control_cyclic.cpp

Have you tried it? Is there something wrong with it?

I am not sure i understand what I am supposed to look at in the link you provided, and I don't know what the issue is exactly. 

Best,
Felix

**Comment by ChanSir-QZ** [comment]
Hi @felixmaisonneuve ,
I have tried the example on how to use the torque control in kortex repo. It is ok.
And i was wandering if i could control the robotic arm based torque control using ROS. Sorry for mine pool knowledge and proposing an implicit issue.

**Comment by felixmaisonneuve** [comment]
No, it is not possible.

Unfortunately, the torque control mode is only available in low level servoing mode, which is not available in our ROS stack. The only way to use the torque control mode is by using the API directly. 

Best,
Felix

**Comment by ChanSir-QZ** [comment]
> 

Thank you for your reply. 

Kind regard,

Chen
