### ISSUE TITLE
ros-kortex not working well in VMWare

### ISSUE THREAD

**Issue by TropicalPenguinn** [Kinovarobotics/ros_kortex#246]
Hello 

I am doing a project related to ros-kortex Gazebo in VMWare 16. Currently, I am conducting tests on Ubuntu 18.04 and 16.04 at the same time. In the case of Ubuntu 18.04 (melodic), Gen3-lite and Gen3 working well in Gazebo. However, in the case of 16.04(kinetic), I got erros. I checked from readme file that ros-kortex is tested in kinetic and ubuntu 16.04. But it doesn't work well in VMWare. I wonder if ros-kortex is not supported in VMWare. 

conan config set general.revisions_enabled=1
conan profile new default --detect > /dev/null
conan profile update settings.compiler.libcxx=libstdc++11 default
rosdep install --from-paths src --ignore-src -y

Moreover,I got erros when the above code into the terminal. 

In the case of 
`
conan config set general.revisions_enabled=1
conan profile new default --detect > /dev/null
conan profile update settings.compiler.libcxx=libstdc++11 default
`
they requires Jinja2>=3.0 but newest version of jinja in ubuntu 16.04 is under that requirement. and can't upgrade through terminal. 

I wonder if this is also because it was run on VMWare. 

![20220728_220240](https://user-images.githubusercontent.com/75155964/181511701-c87412ba-06c2-49e9-9f1a-6c198ba1ffa2.png)

python version 3.5.2
vmware 16
ubuntu 16.04
ros kinetic

**Comment by felixmaisonneuve** [comment]
Hi @LeeJeongWoon-Workout,

What kind of errors do you have on Ubuntu16.04? 
Officially, Ubuntu16.04 and ROS-Kinetic are not supported anymore, however the melodic-devel branch was working with ROS-Kinetic, like you mentionned. 
I have seen problems related to VMs, but it is usually communication problems. I am not sure if this is the case or if the issue is related to VMware.
You could try using the kinetic-devel branch, which was tested on ROS-Kinetic.

About your Jinja2, it is possible the minimum required version was increased since we tested the Kortex driver on Ubuntu16. I am not sure is this package is very usefull, you could probably make it work with a previous Jinja2 version without having to worry about it. This package is downloaded by conan to operate te kortex driver. This is not a VMware issue.

Regards,
Felix
