### ISSUE TITLE
Change base to endeffector transform

### ISSUE THREAD

**Issue by AlfaKeNTAvR** [Kinovarobotics/ros_kortex#256]
## Description

We are looking for a way to modify transform between the base and the endeffector (this is our assumption about the solution). Our Kinova Gen3 robotic is mounted at an angle and we would like to make endeffector coordinate system be still parallel to the ground (currently Z-axis is tilted with the mount angle).

## Version

ROS distribution : Noetic

Branch and commit you are using : noetic-devel

## Expected behavior

Robot arm mounted at an angle, but the tool coordinate system is still parallel to the ground.

**Comment by felixmaisonneuve** [comment]
Hi @AlfaKeNTAvR,

I think what you are looking for is to change the Gravity Vector.
It is possible to change it va ROS, but I think the fastest way to do it is via the WebApp of the arm in Configurations->Robots->Base->Gravity Vector.

Try that first and get back to me if it doesn't work.

Regards,
Felix

**Comment by AlfaKeNTAvR** [comment]
Hi @felixmaisonneuve,

This did not help, coordinate system is still the same (we set the gravity vector to X:-4,905, Z:-4,905). I tried using Xbox controller connected to the robot's USB and publishing to the rostopic.

![image](https://user-images.githubusercontent.com/64020106/192843339-0d536fd9-9ebe-4aed-a23f-1df2589b405e.png)

![image](https://user-images.githubusercontent.com/64020106/192843837-32d97e23-28a3-49ed-9d30-9808b127d7b3.png)

Best regards,
Nikita

**Comment by felixmaisonneuve** [comment]
Since you are using ROS, you should look into [TF2](http://wiki.ros.org/tf2) that allow you to do this kind of computation.
I am not very familiar with this package so I am not sure how to use it and all, but I will do my best to help you if you have questions.

I see references to TF in our launch files. This might be a good starting point : 
https://github.com/Kinovarobotics/ros_kortex/blob/7ba75b3e6293fe4af9fe64f35e877d1ff2613360/kortex_move_it_config/gen3_move_it_config/launch/demo.launch#L26

**Comment by felixmaisonneuve** [comment]
Hi @AlfaKeNTAvR,

can we close this issue?
Did you manage to make your system work using TF2?

I will close this issue in a couple weeks if I do not get an answer from you

Regards,
Felix
