### ISSUE TITLE
Error in kortex_description

### ISSUE THREAD

**Issue by RaduCorcodel** [Kinovarobotics/ros_kortex#30]
When I launch `roslaunch kortex_description display.launch` I get the following error:

`[ERROR] [1562104136.827489851]: The STL file 'package://kortex_description/meshes/EndEffector_Link.STL' is malformed. It appears to be a binary STL file but does not contain enough data for the 80 byte header and 32-bit integer triangle count.
[ERROR] [1562104136.827520627]: Failed to load file [package://kortex_description/meshes/EndEffector_Link.STL]
[ERROR] [1562104136.827701138]: Could not load model 'package://kortex_description/meshes/EndEffector_Link.STL' for link 'EndEffector_Link': OGRE EXCEPTION(6:FileNotFoundException): Cannot locate resource package://kortex_description/meshes/EndEffector_Link.STL in resource group Autodetect or any other group. in ResourceGroupManager::openResource at /build/ogre-1.9-mqY1wq/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreResourceGroupManager.cpp (line 756)`

The first line says the EndEffector_Link.STL is malformed, would that be the problem? And if so, do we have access to a CAD model in SolidWorks or the like, to save a fresh version of the STL file myself?

**Comment by alexvannobel** [comment]
Hi @RaduCorcodel ,

We resolved this problem when refactoring the kortex_description package in the [kinetic-devel](https://github.com/Kinovarobotics/ros_kortex/tree/kinetic-devel) branch. If you use this branch instead of master you should not have this problem.
In the meantime I will open a PR to the master branch to propagate the fix. 

Let me know if this helps!
Cheers,
Alex
