### ISSUE TITLE
Is the low-level control services available in the default kortex_driver package?

### ISSUE THREAD

**Issue by XuRuoyuRoy** [Kinovarobotics/ros_kortex#70]
I want to do low level control. but I can't find any services in the source code of the kortex_driver package. So is that available by default? If it is not generated in the provided code, is there any tutorial or example to state it more clear and in detail?

**Comment by gstlaurentkinova** [comment]
Hi @XuRuoyuRoy,

Low-level control is not available through the ROS1 interface because of real-time issues. Currently the ROS1 implementation does not integrate real-time capabilities with the Gen3 arms.

As such, the services for low-level control are disabled in the kortex_driver package. I suggest you look into the Api examples (https://github.com/Kinovarobotics/kortex) for low-level examples using the Kortex Api.

I hope this answers your question.

Best,

Gabriel

**Comment by polthergeist** [comment]
Hi @XuRuoyuRoy, I was wondering, fo you have any other question regarding this thread or we can close it?

**Comment by XuRuoyuRoy** [comment]
No，feel free to close that， thanks for your help?.&nbsp;
 
---Original---
